PIC-3293 Remove AWS access id and secret
ministryofjustice/pre-sentence-service pull request #207
Opened 2023-09-12 14:04 UTC by cairnsp

2023-09-12 14:37 UTC, vb-moj approved these changes

2023-09-12 14:38 UTC, vb-moj requested changes
Unit test is failing.

2023-09-13 09:02 UTC, johnyfarrar approved these changes
LGTM - does this need any code changes?

2023-09-13 14:33 UTC, rschallapalli commented on server/services/eventService.ts
> +// import { getDefaultRoleAssumerWithWebIdentity } from '@aws-sdk/client-sts'
Remove these?

2023-09-13 15:03 UTC, rschallapalli approved these changes

2023-09-13 15:09 UTC, merged